// src/components/TagBar/tagData.ts

export const TAG_SEGMENTS = {
  temporal: [
    'De dia',
    'De noite',
    'Amanhã',
    'Hoje',
    'Véspera',
    'Feriado',
    'Fim de semana',
    'Acontecendo hoje',
    'Acontecendo agora',
    'Nos próximos 3 dias',
    'Neste fim de semana',
    'Próximo sábado',
    'Próximo domingo',
    'Pôr do sol',
    'Depois das 23h',
    'Antes do almoço',
    'Depois do trabalho',
    'Madrugada',
    'Fim de tarde',
    'A partir das 20h',
    'Até meia-noite',
    'Semana que vem',
    'Próximo feriado',
    'Noite inteira',
    'Turno da manhã',
    'Turno da tarde',
    'Evento'
  ],
  estilo: [
    'Open bar',
    'Open food',
    'Festa temática',
    'Festa de rua',
    'Feira de rua',
    'Bloco de rua',
    'Rolezinho',
    'Luau',
    'Microlive',
    'Show acústico',
    'DJ',
    'DJ set',
    'Karaokê',
    'Quiz',
    'Stand-up',
    'Jam session',
    'Casa de festa',
    'Festa na piscina',
    'Pool party',
    'Rooftop',
    'Terraco',
    'Disco',
    'Flash party',
    'After party',
    'Sunset',
    'Weekender',
    'Festival',
    'Rave',
    'Festa',
    'Electro jam',
    'Festa colaborativa',
    'Festa retrô',
    'Live DJ battle'
  ],
  cultura: [
    'Exposicao',
    'Expo pop-up',
    'Galeria',
    'Cinema',
    'Cinema ao ar livre',
    'Sarau',
    'Poesia',
    'Contação de histórias',
    'Workshop',
    'Performance',
    'Live painting',
    'Batalha',
    'Campeonato',
    'Feira',
    'Feirinha',
    'Feira de rua',
    'Mostra',
    'Mostra audiovisual',
    'Intervenção urbana',
    'Instalação',
    'Instalação imersiva',
    'Cine',
    'Clube do livro',
    'Arte digital',
    'Teatro',
    'Teatro de rua',
    'Roda de leitura',
    'Oficina',
    'Oficina criativa'
  ],
  gastronomia: [
    'Food truck',
    'Praça de alimentação',
    'Degustação',
    'Combo',
    'Petisco',
    'Artesanal',
    'Cozinha de rua',
    'Bar',
    'Pop-up bar',
    'Cerveja',
    'Cerveja artesanal',
    'Chopp',
    'Drink',
    'Drink exclusivo',
    'Mixologia',
    'Cocktail',
    'Rodízio',
    'Rodízio de drinks',
    'Vinho',
    'Degustação',
    'Café',
    'Café especial',
    'Brunch',
    'Brunch coletivo',
    'Feira gastronômica',
    'Churrasco',
    'Churras gourmet',
    'Mesa compartilhada',
    'Piquenique',
    'Festival',
    'Festival de sabores',
    'Menu experimental',
    'Noite de tapas',
    'Doces',
    'Doces artesanais',
    'Bar itinerante'
  ],
  musica: [
    'Ao vivo',
    'Música ao vivo',
    'Banda',
    'Banda cover',
    'Acústico',
    'MPB acústica',
    'Samba',
    'Samba de raiz',
    'Rock',
    'Pop',
    'Funk',
    'Funk carioca',
    'Pagode de mesa',
    'Electronica',
    'House',
    'Techno',
    'Pagode',
    'Indie',
    'Jazz',
    'Chorinho',
    'Trap ',
    'Reggae',
    'Afrobeat',
    'Hip-hop',
    'Sertanejo',
    'Violino',
    'Guitarra',
    'Groove'
  ],
  ambiente: [
    'Ao ar livre',
    'Pé na areia',
    'Vista para o mar',
    'Rooftop',
    'Jardim',
    'Pátio',
    'Jardim suspenso',
    'Pátio interno',
    'Mezanino',
    'Subsolo',
    'Iluminação natural',
    'Decoração temática',
    'Lounge',
    'Dance floor',
    'Palco',
    'Palco improvisado',
    'Varanda',
    'Cabana',
    'Porão',
    'Deck',
    'Tenda',
    'Galpão',
    'Instagramável',
    'Cenário instagramável',
    'Ambiente sensorial',
    'VIP',
    'Área VIP'
  ],
  perks: [
    'Entrada franca',
    'Lista VIP',
    'Desconto',
    'Desconto antecipado',
    'Happy Hour',
    'Happy hour extendido',
    'Open bar',
    'Open bar limitado',
    'Primeira bebida grátis',
    'Cashback',
    'Estacionamento',
    'Estacionamento grátis',
    'Pet friendly',
    'Acessível',
    'Banheiro unissex',
    'Wi-Fi',
    'Bingo',
    'Água grátis',
    'Fila rápida',
    'Copo reutilizável',
    'Área climatizada',
    'Cashless',
    'Brinde'
  ],
  publico: [
    'Grupos',
    'Para casais',
    'Para solteiros',
    'Grupos de amigos',
    'After work',
    'Universitários',
    'LGBTQ+',
    'Adulto',
    'Infantil',
    'Sem filhos',
    'Criativo',
    'Nômade digital',
    'Família',
    'Turistas',
    'Público',
    'Público alternativo',
    'Público premium',

    'Fitness',
    'Gamer',
    'Moradores locais'
  ],
  vibe: [
    'Descontraído',
    'Alto astral',
    'Intimista',
    'Animado',
    'Brega',
    'Vintage',
    'Urbano',
    'Tropical',
    'Épico',
    'Surpreendente',
    'Inesperado',
    'Instagramável',
    'Minimalista',
    'Misterioso',
    'Futurista',
    'Orgânico',
    'Excêntrico',
    'Brilhante',
    'Imersivo',
    'Relaxado',
    'Ritualístico',
    'Sensorial',
    'Acolhedor'
  ],

  promocoes: [
    'Pague 1 leve 2',
    'Happy Hour em dobro',
    'Desconto surpresa',
    'Promoção',
    'Promoção relâmpago',
    'Combo',
    'Combo festa',
    'Entrada gratuita',
    'Primeira rodada grátis',
    'Desconto antecipado',
    'Lista VIP aberta',
    'Brinde exclusivo',
    'Dose dupla',
    'Cashback progressivo',
    'Cupom para próxima edição',
    'Upgrade grátis',
    'Promo válida até meia-noite',
    'Drink em dobro',
    'Rodada de shots',
    'Sorteio no evento',
    'Brindes temáticos',
    'Metade do preço',
    'Combo amigos'
  ]
};




/* 1. same random order on every reload */
const shuffleFixed = <T,>(arr: T[]): T[] => {
  // simple 32-bit seedable PRNG
  let s = 0x6f4a7d9b;
  const rand = () => (s = Math.imul(s, 0x85ebca6b) + 0x1b873593) >>> 0;
  const a = [...arr];
  for (let i = a.length - 1; i > 0; i--) {
    const j = rand() % (i + 1);
    [a[i], a[j]] = [a[j], a[i]];
  }
  return a;
};
export const ALL_TAGS = shuffleFixed([...new Set(Object.values(TAG_SEGMENTS).flat())]);

/* 2. alphabetical (existing) */
export const ALL_TAGS_ALPHABETIC = [...ALL_TAGS].sort((a, b) => a.localeCompare(b));